FROM continuumio/miniconda3

RUN conda info;
RUN conda create --name hail python=3.7
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install openjdk-8-jdk -y
# RUN conda activate hail

# Make sure it's Python 3.7.3
RUN python -V
RUN python -m pip install hail
RUN python -m pip install ipywidgets
RUN python -m pip install jupyterlab
ADD ./start.sh /start.sh
RUN conda init bash
EXPOSE 8888

RUN mkdir /notebooks

WORKDIR notebooks

ENTRYPOINT ["sh", "/start.sh"]
